// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3My2J1rMnh1JEMR07NB-mGtAObG8FI_U',
    appId: '1:443749141340:web:52d6767649057fa7e10f99',
    messagingSenderId: '443749141340',
    projectId: 'flutter-cookbook-b1fc5',
    authDomain: 'flutter-cookbook-b1fc5.firebaseapp.com',
    storageBucket: 'flutter-cookbook-b1fc5.firebasestorage.app',
    measurementId: 'G-B7JJZ3ZKXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkXSB4XHFy3eF02zkpoOwrEwdBIcM_T_Q',
    appId: '1:443749141340:android:b17c1b448af549f7e10f99',
    messagingSenderId: '443749141340',
    projectId: 'flutter-cookbook-b1fc5',
    storageBucket: 'flutter-cookbook-b1fc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBXUoEfijHjE8-aaUTD3ZonKt7HvX2JrY',
    appId: '1:443749141340:ios:5b0a4879ffdf7a89e10f99',
    messagingSenderId: '443749141340',
    projectId: 'flutter-cookbook-b1fc5',
    storageBucket: 'flutter-cookbook-b1fc5.firebasestorage.app',
    iosBundleId: 'com.example.01FirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBXUoEfijHjE8-aaUTD3ZonKt7HvX2JrY',
    appId: '1:443749141340:ios:5b0a4879ffdf7a89e10f99',
    messagingSenderId: '443749141340',
    projectId: 'flutter-cookbook-b1fc5',
    storageBucket: 'flutter-cookbook-b1fc5.firebasestorage.app',
    iosBundleId: 'com.example.01FirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3My2J1rMnh1JEMR07NB-mGtAObG8FI_U',
    appId: '1:443749141340:web:eb609628fa6d59b6e10f99',
    messagingSenderId: '443749141340',
    projectId: 'flutter-cookbook-b1fc5',
    authDomain: 'flutter-cookbook-b1fc5.firebaseapp.com',
    storageBucket: 'flutter-cookbook-b1fc5.firebasestorage.app',
    measurementId: 'G-9JDT2BJTDP',
  );

}